seed_everything: 7
trainer:
  logger: true
  checkpoint_callback: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
      log_momentum: false
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      dirpath: null
      filename: '{epoch}-{step}-{val_ExpRate:.4f}'
      monitor: val_ExpRate
      verbose: false
      save_last: null
      save_top_k: 1
      save_weights_only: false
      mode: max
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      period: null
      every_n_val_epochs: null
  default_root_dir: null
  gradient_clip_val: 0.0
  gradient_clip_algorithm: norm
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: null
  gpus: 0, 1, 2, 3
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 5
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 180
  min_epochs: null
  max_steps: null
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: 100
  log_every_n_steps: 50
  accelerator: ddp
  sync_batchnorm: false
  precision: 32
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  truncated_bptt_steps: null
  resume_from_checkpoint: /home/bml/storage/mnt/v-c615a05aea3047cd/org/users/zouzichen/CoMER/CoMER/lightning_logs/version_34/checkpoints/epoch=109-step=86359-val_ExpRate=0.6052.ckpt
  profiler: null
  benchmark: false
  deterministic: true
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  terminate_on_nan: false
  auto_scale_batch_size: false
  prepare_data_per_node: true
  plugins:
  - class_path: pytorch_lightning.plugins.DDPPlugin
    init_args:
      parallel_devices: null
      num_nodes: null
      cluster_environment: null
      sync_batchnorm: null
      ddp_comm_state: null
      output_device: null
      dim: 0
      broadcast_buffers: true
      process_group: null
      bucket_cap_mb: 25.0
      find_unused_parameters: false
      check_reduction: false
      gradient_as_bucket_view: false
  amp_backend: native
  amp_level: O2
  distributed_backend: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
model:
  d_model: 256
  growth_rate: 24
  num_layers: 16
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  dropout: 0.3
  dc: 32
  cross_coverage: true
  self_coverage: true
  beam_size: 10
  max_len: 200
  alpha: 1.0
  early_stopping: false
  temperature: 1.0
  learning_rate: 0.08
  patience: 20
data:
  zipfile_path: data.zip
  test_year: '2014'
  train_batch_size: 8
  eval_batch_size: 4
  num_workers: 8
  scale_aug: true
